services:
  db:
    container_name: matjum-db
    build:
      context: ./Dockerfiles/postgis
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432' # Host:Container 내부 포트
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - matjum-network
  server:
    container_name: matjum-server
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./Dockerfiles/server
    env_file:
      - .env
    ports:
      - '3000:3000'
    init: true
    restart: unless-stopped # 예기치 않은 종료 시 재시작
    networks:
      - matjum-network

volumes:
  db_data:

networks:
  matjum-network:
    name: matjum-network
    driver: bridge
