services:
  db:
    container_name: matjum_db
    image: postgres:16.4-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432' # Host:Container 내부 포트
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    container_name: matjum_server
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    init: true
    restart: unless-stopped # 예기치 않은 종료 시 재시작

volumes:
  db_data:
